services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/stocks_db
    command: uvicorn stock_prediction_api:api --host 0.0.0.0 --port 8000 --reload
    working_dir: /app

  test:
    build:
      context: .
      dockerfile: Dockerfile_test
    volumes:
      - .:/app
    depends_on:
      - api  # Ensure that the API is running before running tests
