version: '3'
services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/stocks_db
    depends_on:
      - db
      - prometheus
    command: uvicorn stock_prediction_api:api --host 0.0.0.0 --port 8000 --reload
    working_dir: /app

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: stocks_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

  cron_job:
    build: .
    command: /bin/sh -c "while :; do python cron_job.py; sleep 1800; done"  # Runs every 30 minutes
    depends_on:
      - api

volumes:
  db_data:
  grafana_data:


