# Base image
FROM python:3.10

# Working directory
WORKDIR /app

# Copying requirements file and installation of dependencies
COPY requirements.txt ./
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

# Copy the API code and test code to the container
COPY . /app

# Install testing dependencies (if any are separate)
RUN pip install pytest pytest-asyncio fastapi[all]

# Command to run tests
CMD ["pytest", "test_api.py"]
